version: '3.8'
services:
  db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=directus
      - MYSQL_ROOT_PASSWORD=sample
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db:
    driver: local
